#!/usr/bin/env python3
"""
Reads Newman JSON results and writes an issues report covering:
  - Wrong status codes (failed "Status is X" assertions)
  - Message quality (failed "Error message identifies the problem field" assertions)

Generated by /qa-api-test-setup from .claude/templates/generate-issues.py.

Usage:
  python3 generate-issues.py <timestamp> <results.json> <output-dir> <project-slug> <project-name>

Args:
  timestamp     -- run timestamp, used in the output filename
  results.json  -- Newman's --reporter-json-export file
  output-dir    -- where to write the .txt report (e.g. collection-run-issues)
  project-slug  -- lowercase hyphenated slug used in the filename (e.g. myproject)
  project-name  -- display name used in the report header (e.g. MyProject)
"""

import json
import sys
import os
import re

SUCCESS_WORDS = re.compile(
    r'\b(created|updated|deleted|saved|success|completed|processed|done|added|removed|applied)\b', re.I
)

def extract_actual_msg(error_message):
    m = re.search(r'Vague error: "([^"]*)"', error_message or '')
    return m.group(1) if m else '(could not extract message)'

def parse_expected_statuses(assertion_name):
    codes = re.findall(r'\b(\d{3})\b', assertion_name)
    return [int(c) for c in codes]

def classify_status_issue(expected_statuses, actual_status, request_name):
    name_lower = request_name.lower()
    expected_str = ' or '.join(str(s) for s in expected_statuses)

    if actual_status < 400 and all(s >= 400 for s in expected_statuses):
        if 'xss' in name_lower or 'sql' in name_lower or 'injection' in name_lower or 'payload' in name_lower:
            return (
                f"Expected HTTP {expected_str} (rejection) but got HTTP {actual_status}. "
                "The API accepted a potentially dangerous payload (XSS or SQL injection) "
                "without sanitising or rejecting it. This is a security vulnerability."
            )
        if 'duplicate' in name_lower or 'conflict' in name_lower:
            return (
                f"Expected HTTP {expected_str} (Conflict) but got HTTP {actual_status}. "
                "The API accepted a duplicate resource when it should have detected the conflict "
                "and rejected it. Duplicate data can now exist silently in the system."
            )
        return (
            f"Expected HTTP {expected_str} but got HTTP {actual_status}. "
            "The API accepted a request it should have rejected."
        )

    if actual_status >= 400 and all(s < 400 for s in expected_statuses):
        return (
            f"Expected HTTP {expected_str} (success) but got HTTP {actual_status}. "
            "The API rejected a request that should have succeeded. "
            "This may indicate a test data issue or an API regression."
        )

    return (
        f"Expected HTTP {expected_str} but got HTTP {actual_status}. "
        "The server returned an unexpected status code."
    )

def classify_msg_issue(msg, status_code, request_name):
    msg_lower = msg.lower().strip()

    if not msg_lower:
        return (
            "The API returned no message at all. "
            "The client has no way to know what failed or how to fix it."
        )

    if SUCCESS_WORDS.search(msg) and status_code and status_code >= 400:
        if status_code == 409:
            return (
                f"HTTP {status_code} (Conflict) means the server detected a problem, "
                f"but the message says \"{msg}\" - a success message. "
                "The status code and message directly contradict each other. "
                "A developer reading the message would think the operation succeeded."
            )
        return (
            f"HTTP {status_code} means the request failed, "
            f"but the message says \"{msg}\" - a success message. "
            "This suggests the API accepted input it should have rejected "
            "(e.g. dangerous payload, invalid value) without telling the user what was wrong. "
            "This may also be a security issue if the input contains XSS or SQL injection."
        )

    if SUCCESS_WORDS.search(msg) and status_code and status_code < 400:
        name_lower = request_name.lower()
        expected_match = re.search(r'\((\d{3})\)$', request_name.strip())
        expected_status = int(expected_match.group(1)) if expected_match else None

        if 'xss' in name_lower or 'sql' in name_lower or 'injection' in name_lower or 'payload' in name_lower:
            return (
                f"The API accepted the request and returned \"{msg}\". "
                "This test submitted a potentially dangerous payload (XSS or SQL injection). "
                "The API should sanitise or reject such input - accepting it silently is a security risk."
            )
        if 'duplicate' in name_lower or 'conflict' in name_lower:
            return (
                f"The API accepted a duplicate resource and returned \"{msg}\" with HTTP {status_code}. "
                f"The server should have rejected this with HTTP {expected_status or 409} (Conflict) "
                "because a resource with the same name already exists. "
                "This allows duplicate data to be created silently."
            )
        return (
            f"The API accepted the request and returned \"{msg}\" with HTTP {status_code}. "
            f"This test expected HTTP {expected_status or '4xx'} (a failure response), "
            "but the server treated the request as successful. "
            "The input should have been rejected."
        )

    if len(msg_lower) < 20:
        return (
            f"The message \"{msg}\" is too short to be useful. "
            "It does not identify which field failed, why it failed, "
            "or what the user should do to fix it."
        )

    return (
        f"The message \"{msg}\" does not clearly identify the affected field or value, "
        "does not explain the reason for failure, "
        "and does not tell the user what input is expected. "
        "A user seeing this message cannot tell what they did wrong."
    )

def main():
    if len(sys.argv) < 6:
        print("Usage: generate-issues.py <timestamp> <results.json> <output-dir> <project-slug> <project-name>")
        sys.exit(1)

    timestamp     = sys.argv[1]
    results_path  = sys.argv[2]
    output_dir    = sys.argv[3]
    project_slug  = sys.argv[4]
    project_name  = sys.argv[5]

    if not os.path.exists(results_path):
        print(f"Results file not found: {results_path}")
        sys.exit(1)

    with open(results_path) as f:
        data = json.load(f)

    executions = data.get('run', {}).get('executions', [])
    issues = []

    for ex in executions:
        request_name = ex.get('item', {}).get('name', 'Unknown')

        url = ''
        try:
            raw_url = ex.get('request', {}).get('url', {})
            if isinstance(raw_url, str):
                url = raw_url
            elif isinstance(raw_url, dict):
                url = raw_url.get('raw') or raw_url.get('href') or (
                    raw_url.get('protocol', 'https') + '://' +
                    '.'.join(raw_url.get('host', [])) + '/' +
                    '/'.join(raw_url.get('path', []))
                )
        except Exception:
            pass

        method      = ex.get('request', {}).get('method', '')
        status_code = ex.get('response', {}).get('code')

        for assertion in ex.get('assertions', []):
            aname = assertion.get('assertion', '')
            error = assertion.get('error')

            if re.match(r'^Status is \d', aname) and error:
                expected = parse_expected_statuses(aname)
                if expected and status_code not in expected:
                    issues.append({
                        'type':               'Status mismatch',
                        'request':            request_name,
                        'method':             method,
                        'url':                url,
                        'status':             status_code,
                        'expected_statuses':  expected,
                        'reason':             classify_status_issue(expected, status_code, request_name),
                    })

            elif 'Error message identifies the problem field' in aname and error:
                actual_msg = extract_actual_msg(error.get('message', ''))
                try:
                    resp_body = ex.get('response', {}).get('body', '') or ''
                    resp_json = json.loads(resp_body)
                    full_msg = (
                        resp_json.get('error', {}).get('message') or
                        resp_json.get('message') or
                        actual_msg
                    )
                except Exception:
                    full_msg = actual_msg

                issues.append({
                    'type':       'Message quality',
                    'request':    request_name,
                    'method':     method,
                    'url':        url,
                    'status':     status_code,
                    'actual_msg': full_msg,
                    'reason':     classify_msg_issue(full_msg, status_code, request_name),
                })

    output_file = os.path.join(output_dir, f'{project_slug}-issues-{timestamp}.txt')
    os.makedirs(output_dir, exist_ok=True)

    with open(output_file, 'w') as f:
        f.write(f'{project_name} API - Issues Report\n')
        f.write(f'Run: {timestamp}\n')
        f.write('=' * 65 + '\n\n')

        if not issues:
            f.write('No issues found.\n')
            f.write('All status codes and error messages are correct.\n')
        else:
            f.write(f'Total issues found: {len(issues)}\n\n')
            for i, issue in enumerate(issues, 1):
                f.write(f'ISSUE #{i}\n')
                f.write(f'Type     : {issue["type"]}\n')
                f.write(f'Request  : {issue["request"]}\n')
                f.write(f'Endpoint : {issue["method"]} {issue["url"]}\n')
                if issue['type'] == 'Status mismatch':
                    expected_str = ' or '.join(str(s) for s in issue['expected_statuses'])
                    f.write(f'Status   : HTTP {issue["status"]} (expected {expected_str})\n')
                    f.write(f'Why      : {issue["reason"]}\n')
                else:
                    f.write(f'Status   : HTTP {issue["status"]}\n')
                    f.write(f'Actual   : "{issue["actual_msg"]}"\n')
                    f.write(f'Why      : {issue["reason"]}\n')
                    f.write( 'Expected : Message should name the affected field, explain the reason,\n')
                    f.write( '           and tell the user what input is accepted.\n')
                    f.write( '           e.g. "name contains invalid characters - XSS payload not allowed"\n')
                    f.write( '                "role name already exists - choose a different name"\n')
                f.write('-' * 65 + '\n\n')

        f.write('\nGenerated by generate-issues.py\n')

    print(f'Issues report: {output_file}')
    return len(issues)

if __name__ == '__main__':
    count = main()
    sys.exit(0)
