#!/bin/bash
# Run __PROJECT_NAME__ API automated tests via Newman.
# Generated by /qa-api-test-setup from .claude/templates/run-tests.sh.
# Usage: ./run-tests.sh

set -e

PROJECT_SLUG="__PROJECT_SLUG__"
PROJECT_NAME="__PROJECT_NAME__"
BASE_URL="__BASE_URL__"
HEALTH_PATH="__HEALTH_PATH__"
HEALTH_AUTH_HEADER="__HEALTH_AUTH_HEADER__"

COLLECTION="${PROJECT_SLUG}-collection.json"
ENVIRONMENT="newman-env.json"
REPORT_DIR="newman-reports"
ISSUES_DIR="collection-run-issues"
TIMESTAMP=$(date +"%d-%m-%Y_%Hh%Mm%Ss")

REPORT_FILE="$REPORT_DIR/${PROJECT_SLUG}-report-$TIMESTAMP.html"
RESULTS_JSON="$REPORT_DIR/${PROJECT_SLUG}-results-$TIMESTAMP.json"
ISSUES_FILE="$ISSUES_DIR/${PROJECT_SLUG}-issues-$TIMESTAMP.txt"

# Check server reachability first - saves you from a wall of 401s if the API is down
echo "Checking API server..."
HEALTH_CHECK_CURL="curl -s --max-time 5 ${BASE_URL}${HEALTH_PATH} -o /dev/null -w %{http_code}"
[ -n "$HEALTH_AUTH_HEADER" ] && HEALTH_CHECK_CURL="$HEALTH_CHECK_CURL -H \"$HEALTH_AUTH_HEADER\""
if ! eval "$HEALTH_CHECK_CURL" | grep -qE "^(200|401)"; then
  echo "ERROR: API server unreachable at $BASE_URL"
  echo "Check your VPN or network connection and try again."
  exit 1
fi
echo "Server is up. Running tests..."

mkdir -p "$REPORT_DIR" "$ISSUES_DIR"

# Run the suite - NEVER --bail; the HTML report must capture every failure in one pass
NEWMAN_FAILED=0
newman run "$COLLECTION" \
  --environment "$ENVIRONMENT" \
  --reporters cli,htmlextra,json \
  --reporter-htmlextra-export "$REPORT_FILE" \
  --reporter-htmlextra-title "${PROJECT_NAME} API Test Report $TIMESTAMP" \
  --reporter-json-export "$RESULTS_JSON" \
  --delay-request 500 \
  --timeout-request 25000 || NEWMAN_FAILED=1

echo ""
echo "HTML report : $REPORT_FILE"

# Generate parsed issues report (status mismatches + message quality)
if [ -f "generate-issues.py" ] && command -v python3 &>/dev/null && [ -f "$RESULTS_JSON" ]; then
  python3 generate-issues.py "$TIMESTAMP" "$RESULTS_JSON" "$ISSUES_DIR" "$PROJECT_SLUG" "$PROJECT_NAME"
  if [ -f "$ISSUES_FILE" ]; then
    ISSUE_COUNT=$(grep -c "^ISSUE #" "$ISSUES_FILE" 2>/dev/null || echo 0)
    if [ "$ISSUE_COUNT" -gt 0 ]; then
      echo "Issues report: $ISSUES_FILE ($ISSUE_COUNT issue(s) found)"
      open "$ISSUES_FILE" 2>/dev/null
    else
      echo "No status or message-quality issues found."
    fi
  fi
elif [ ! -f "generate-issues.py" ]; then
  echo "Note: generate-issues.py not found - skipping parsed issues report."
fi

open "$REPORT_FILE" 2>/dev/null || echo "Open the report at: $REPORT_FILE"

[ "$NEWMAN_FAILED" -eq 1 ] && exit 1 || exit 0
